### ISSUE TITLE
Issue in running npm run dev

### ISSUE THREAD

**Issue by PurushothamanSrikanth** [devandres-tech/Netflix-Clone#22]
`D:\Project\watchit>npm run dev`

I'm getting this error while running the command `npm run dev` in cmd. Can someone help me out with this?

```> webpack-basics@1.0.0 dev D:\Project\watchit
> webpack-dev-server --mode development --config webpack.config.js --open

internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module 'webpack/bin/config-optimist'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\Project\watchit\node_modules\webpack-dev-server\bin\webpack-dev-server.js:24:1)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webpack-basics@1.0.0 dev: `webpack-dev-server --mode development --config webpack.config.js --open`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webpack-basics@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jispu\AppData\Roaming\npm-cache\_logs\2020-11-17T18_45_28_528Z-debug.log```

**Comment by devandres-tech** [comment]
This should have been fixed with the latest Webpack 5 updates.
